In [1]:
import pandas as pd #importazione libreria PANDAS

#lettura e importazione csv
results = pd.read_csv("results.csv")
races = pd.read_csv("races.csv")
constructors = pd.read_csv("constructors.csv")
drivers = pd.read_csv("drivers.csv")

In [2]:
#fase EDA (head)
display(results.head(5))
print("_________________________________")
display(races.head(5))
print("_________________________________")
display(constructors.head(5))
print("_________________________________")
display(drivers.head(5))
print("_________________________________")

,race_id,driver_id,constructor_id,grid,position,position_order,points,laps,status
0,1950_1,farina,alfa,1,1,1,9.0,70,Finished
1,1950_1,fagioli,alfa,2,2,2,6.0,70,Finished
2,1950_1,reg_parnell,alfa,4,3,3,4.0,70,Finished
3,1950_1,cabantous,lago,6,4,4,3.0,68,+2 Laps
4,1950_1,rosier,lago,9,5,5,2.0,68,+2 Laps

_________________________________

  race_id  season  round           race_name        date time    circuit_id
0  1950_1    1950      1  British Grand Prix  1950-05-13  NaN   silverstone
1  1950_2    1950      2   Monaco Grand Prix  1950-05-21  NaN        monaco
2  1950_3    1950      3    Indianapolis 500  1950-05-30  NaN  indianapolis
3  1950_4    1950      4    Swiss Grand Prix  1950-06-04  NaN    bremgarten
4  1950_5    1950      5  Belgian Grand Prix  1950-06-18  NaN           spa

_________________________________

,constructor_id,name,nationality,Wikipedia_url
0,alfa,Alfa Romeo,Swiss,https://en.wikipedia.org/wiki/Alfa_Romeo_in_Fo...
1,lago,Talbot-Lago,French,https://en.wikipedia.org/wiki/Talbot-Lago_T26C
2,era,ERA,British,http://en.espn.co.uk/era/motorsport/team/292.h...
3,maserati,Maserati,Italian,https://en.wikipedia.org/wiki/Maserati_in_moto...
4,alta,Alta,British,https://f1.fandom.com/wiki/Alta_Car_and_Engine...

_________________________________

     driver_id givenName familyName nationality         dob
0       farina      Nino     Farina     Italian  1906-10-30
1      fagioli     Luigi    Fagioli     Italian  1898-06-09
2  reg_parnell       Reg    Parnell     British  1911-07-02
3    cabantous      Yves  Cabantous      French  1904-10-08
4       rosier     Louis     Rosier      French  1905-11-05

_________________________________

In [3]:
#controllo valori nulli
display(results.isna().sum())
print("_________________________________")
display(races.isna().sum())
print("_________________________________")
display(constructors.isna().sum())
print("_________________________________")
display(drivers.isna().sum())
print("_________________________________")

race_id           0
driver_id         0
constructor_id    0
grid              0
position          0
position_order    0
points            0
laps              0
status            0
dtype: int64

_________________________________

race_id         0
season          0
round           0
race_name       0
date            0
time          731
circuit_id      0
dtype: int64

_________________________________

constructor_id      0
name                0
nationality         0
Wikipedia_url     124
dtype: int64

_________________________________

driver_id      0
givenName      0
familyName     0
nationality    0
dob            0
dtype: int64

_________________________________

In [4]:
#info per capire informazioni generali di tutti i datasets
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7600 entries, 0 to 7599
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   race_id         7600 non-null   object
 1   driver_id       7600 non-null   object
 2   constructor_id  7600 non-null   object
 3   grid            7600 non-null   int64
 4   position        7600 non-null   object
 5   position_order  7600 non-null   int64
 6   points          7600 non-null   float64
 7   laps            7600 non-null   int64
 8   status          7600 non-null   object
dtypes: float64(1), int64(3), object(5)
memory usage: 534.5+ KB

In [5]:
races.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1149 entries, 0 to 1148
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   race_id     1149 non-null   object
 1   season      1149 non-null   int64
 2   round       1149 non-null   int64
 3   race_name   1149 non-null   object
 4   date        1149 non-null   object
 5   time        418 non-null    object
 6   circuit_id  1149 non-null   object
dtypes: int64(2), object(5)
memory usage: 63.0+ KB

In [6]:
constructors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   constructor_id  168 non-null    object
 1   name            168 non-null    object
 2   nationality     168 non-null    object
 3   Wikipedia_url   44 non-null     object
dtypes: object(4)
memory usage: 5.4+ KB

In [7]:
drivers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 616 entries, 0 to 615
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   driver_id    616 non-null    object
 1   givenName    616 non-null    object
 2   familyName   616 non-null    object
 3   nationality  616 non-null    object
 4   dob          616 non-null    object
dtypes: object(5)
memory usage: 24.2+ KB

In [8]:
#inizio pulizia dataset races
races = races.drop_duplicates() #rimozione di presunti duplicati
races = races.drop(columns=["time"]) #rimozione di colonne che non servono per l'analisi
races

      race_id  season  round               race_name        date    circuit_id
0      1950_1    1950      1      British Grand Prix  1950-05-13   silverstone
1      1950_2    1950      2       Monaco Grand Prix  1950-05-21        monaco
2      1950_3    1950      3        Indianapolis 500  1950-05-30  indianapolis
3      1950_4    1950      4        Swiss Grand Prix  1950-06-04    bremgarten
4      1950_5    1950      5      Belgian Grand Prix  1950-06-18           spa
...       ...     ...    ...                     ...         ...           ...
1144  2025_20    2025     20  Mexico City Grand Prix  2025-10-26     rodriguez
1145  2025_21    2025     21    São Paulo Grand Prix  2025-11-09    interlagos
1146  2025_22    2025     22    Las Vegas Grand Prix  2025-11-23         vegas
1147  2025_23    2025     23        Qatar Grand Prix  2025-11-30        losail
1148  2025_24    2025     24    Abu Dhabi Grand Prix  2025-12-07    yas_marina

[1149 rows x 6 columns]

In [9]:
#modifico nomi colonne
races = races.rename(columns={"race_id": "RaceID",
                     "season": "Year",
                     "race_name": "Race_Name",
                     "date": "Date",
                     "circuit_id": "CircuitID"})
races

       RaceID  Year  round               Race_Name        Date     CircuitID
0      1950_1  1950      1      British Grand Prix  1950-05-13   silverstone
1      1950_2  1950      2       Monaco Grand Prix  1950-05-21        monaco
2      1950_3  1950      3        Indianapolis 500  1950-05-30  indianapolis
3      1950_4  1950      4        Swiss Grand Prix  1950-06-04    bremgarten
4      1950_5  1950      5      Belgian Grand Prix  1950-06-18           spa
...       ...   ...    ...                     ...         ...           ...
1144  2025_20  2025     20  Mexico City Grand Prix  2025-10-26     rodriguez
1145  2025_21  2025     21    São Paulo Grand Prix  2025-11-09    interlagos
1146  2025_22  2025     22    Las Vegas Grand Prix  2025-11-23         vegas
1147  2025_23  2025     23        Qatar Grand Prix  2025-11-30        losail
1148  2025_24  2025     24    Abu Dhabi Grand Prix  2025-12-07    yas_marina

[1149 rows x 6 columns]

In [10]:
#filtro gli anni da tenere conto per la mia analisi
races = races[races["Year"] >= 2014]
races

       RaceID  Year  round               Race_Name        Date    CircuitID
897    2014_1  2014      1   Australian Grand Prix  2014-03-16  albert_park
898    2014_2  2014      2    Malaysian Grand Prix  2014-03-30       sepang
899    2014_3  2014      3      Bahrain Grand Prix  2014-04-06      bahrain
900    2014_4  2014      4      Chinese Grand Prix  2014-04-20     shanghai
901    2014_5  2014      5      Spanish Grand Prix  2014-05-11    catalunya
...       ...   ...    ...                     ...         ...          ...
1144  2025_20  2025     20  Mexico City Grand Prix  2025-10-26    rodriguez
1145  2025_21  2025     21    São Paulo Grand Prix  2025-11-09   interlagos
1146  2025_22  2025     22    Las Vegas Grand Prix  2025-11-23        vegas
1147  2025_23  2025     23        Qatar Grand Prix  2025-11-30       losail
1148  2025_24  2025     24    Abu Dhabi Grand Prix  2025-12-07   yas_marina

[252 rows x 6 columns]

In [11]:
races.isna().sum() #check valori nulli dopo filtraggio

RaceID       0
Year         0
round        0
Race_Name    0
Date         0
CircuitID    0
dtype: int64

In [12]:
races.loc[:, "Date"] = pd.to_datetime(races["Date"], errors="coerce")

In [13]:
races.info()

<class 'pandas.core.frame.DataFrame'>
Index: 252 entries, 897 to 1148
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   RaceID     252 non-null    object
 1   Year       252 non-null    int64
 2   round      252 non-null    int64
 3   Race_Name  252 non-null    object
 4   Date       252 non-null    object
 5   CircuitID  252 non-null    object
dtypes: int64(2), object(4)
memory usage: 13.8+ KB

In [14]:
races = races.rename(columns={"round": "Round"})

In [15]:
races.to_csv("races_clean.csv", index=False) #salvataggio in un nuovo csv pulito

In [16]:
results.head()
results.info()
results.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7600 entries, 0 to 7599
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   race_id         7600 non-null   object
 1   driver_id       7600 non-null   object
 2   constructor_id  7600 non-null   object
 3   grid            7600 non-null   int64
 4   position        7600 non-null   object
 5   position_order  7600 non-null   int64
 6   points          7600 non-null   float64
 7   laps            7600 non-null   int64
 8   status          7600 non-null   object
dtypes: float64(1), int64(3), object(5)
memory usage: 534.5+ KB

race_id           0
driver_id         0
constructor_id    0
grid              0
position          0
position_order    0
points            0
laps              0
status            0
dtype: int64

In [17]:
#rimuovo i duplicati

In [18]:
results = results.drop_duplicates()

In [19]:
#richiamo le colonne

In [20]:
results.columns

Index(['race_id', 'driver_id', 'constructor_id', 'grid', 'position',
       'position_order', 'points', 'laps', 'status'],
      dtype='object')

In [21]:
results = results.rename(columns={"race_id":"RaceID",
                                  "driver_id":"DriverID",
                                  "constructor_id":"ConstructorID",
                                  "grid":"Grid",
                                  "position":"Position",
                                  "position_order":"PositionOrder",
                                  "points":"Points",
                                  "laps":"Laps",
                                  "status":"Status"})
results

,RaceID,DriverID,ConstructorID,Grid,Position,PositionOrder,Points,Laps,Status
0,1950_1,farina,alfa,1,1,1,9.0,70,Finished
1,1950_1,fagioli,alfa,2,2,2,6.0,70,Finished
2,1950_1,reg_parnell,alfa,4,3,3,4.0,70,Finished
3,1950_1,cabantous,lago,6,4,4,3.0,68,+2 Laps
4,1950_1,rosier,lago,9,5,5,2.0,68,+2 Laps
...,...,...,...,...,...,...,...,...,...
7595,2025_5,stroll,aston_martin,16,16,16,0.0,49,Lapped
7596,2025_5,doohan,alpine,17,17,17,0.0,49,Lapped
7597,2025_5,bortoleto,sauber,20,18,18,0.0,49,Lapped
7598,2025_5,tsunoda,red_bull,8,R,19,0.0,1,Retired
7599,2025_5,gasly,alpine,9,R,20,0.0,0,Retired

In [22]:
#merge tra races e results per importare colonna Year e filtrare
results = results.merge(
    races[["RaceID", "Year"]],
    on="RaceID",
    how="left"
)

In [23]:
#filtro per anno
results = results[results["Year"] >= 2014]

In [24]:
#check
results

,RaceID,DriverID,ConstructorID,Grid,Position,PositionOrder,Points,Laps,Status,Year
6400,2014_1,rosberg,mercedes,3,1,1,25.0,57,Finished,2014.0
6401,2014_1,kevin_magnussen,mclaren,4,2,2,18.0,57,Finished,2014.0
6402,2014_1,button,mclaren,10,3,3,15.0,57,Finished,2014.0
6403,2014_1,alonso,ferrari,5,4,4,12.0,57,Finished,2014.0
6404,2014_1,bottas,williams,15,5,5,10.0,57,Finished,2014.0
...,...,...,...,...,...,...,...,...,...,...
7595,2025_5,stroll,aston_martin,16,16,16,0.0,49,Lapped,2025.0
7596,2025_5,doohan,alpine,17,17,17,0.0,49,Lapped,2025.0
7597,2025_5,bortoleto,sauber,20,18,18,0.0,49,Lapped,2025.0
7598,2025_5,tsunoda,red_bull,8,R,19,0.0,1,Retired,2025.0
7599,2025_5,gasly,alpine,9,R,20,0.0,0,Retired,2025.0

In [25]:
#conversione tipo di dato alla colonna Year
results["Year"] = results['Year'].astype(int)
results

,RaceID,DriverID,ConstructorID,Grid,Position,PositionOrder,Points,Laps,Status,Year
6400,2014_1,rosberg,mercedes,3,1,1,25.0,57,Finished,2014
6401,2014_1,kevin_magnussen,mclaren,4,2,2,18.0,57,Finished,2014
6402,2014_1,button,mclaren,10,3,3,15.0,57,Finished,2014
6403,2014_1,alonso,ferrari,5,4,4,12.0,57,Finished,2014
6404,2014_1,bottas,williams,15,5,5,10.0,57,Finished,2014
...,...,...,...,...,...,...,...,...,...,...
7595,2025_5,stroll,aston_martin,16,16,16,0.0,49,Lapped,2025
7596,2025_5,doohan,alpine,17,17,17,0.0,49,Lapped,2025
7597,2025_5,bortoleto,sauber,20,18,18,0.0,49,Lapped,2025
7598,2025_5,tsunoda,red_bull,8,R,19,0.0,1,Retired,2025
7599,2025_5,gasly,alpine,9,R,20,0.0,0,Retired,2025

In [26]:
results.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1200 entries, 6400 to 7599
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   RaceID         1200 non-null   object
 1   DriverID       1200 non-null   object
 2   ConstructorID  1200 non-null   object
 3   Grid           1200 non-null   int64
 4   Position       1200 non-null   object
 5   PositionOrder  1200 non-null   int64
 6   Points         1200 non-null   float64
 7   Laps           1200 non-null   int64
 8   Status         1200 non-null   object
 9   Year           1200 non-null   int64
dtypes: float64(1), int64(4), object(5)
memory usage: 103.1+ KB

In [27]:
#elimino la colonna Position perchè non ha tutti i valori numerici ed è uguale alla colonna PositionOrder che è totalmente numerica
results = results.drop(columns=["Position"], errors="ignore")

In [28]:
#rinomino colonne per capire meglio
results = results.rename(columns={"Grid":"Starting_Position",
                                  "PositionOrder":"Final_Position"}
                        )
results

,RaceID,DriverID,ConstructorID,Starting_Position,Final_Position,Points,Laps,Status,Year
6400,2014_1,rosberg,mercedes,3,1,25.0,57,Finished,2014
6401,2014_1,kevin_magnussen,mclaren,4,2,18.0,57,Finished,2014
6402,2014_1,button,mclaren,10,3,15.0,57,Finished,2014
6403,2014_1,alonso,ferrari,5,4,12.0,57,Finished,2014
6404,2014_1,bottas,williams,15,5,10.0,57,Finished,2014
...,...,...,...,...,...,...,...,...,...
7595,2025_5,stroll,aston_martin,16,16,0.0,49,Lapped,2025
7596,2025_5,doohan,alpine,17,17,0.0,49,Lapped,2025
7597,2025_5,bortoleto,sauber,20,18,0.0,49,Lapped,2025
7598,2025_5,tsunoda,red_bull,8,19,0.0,1,Retired,2025
7599,2025_5,gasly,alpine,9,20,0.0,0,Retired,2025

In [29]:
#salvo le modifiche in un nouvo file csv pulito
results.to_csv("results_clean.csv", index=False)

In [30]:
#passiamo al dataset constructors
#richiamo l'EDA
print(constructors.head())
print(constructors.info())
print(constructors.isna().sum())

  constructor_id         name nationality  \
0           alfa   Alfa Romeo       Swiss
1           lago  Talbot-Lago      French
2            era          ERA     British
3       maserati     Maserati     Italian
4           alta         Alta     British

                                       Wikipedia_url
0  https://en.wikipedia.org/wiki/Alfa_Romeo_in_Fo...
1     https://en.wikipedia.org/wiki/Talbot-Lago_T26C
2  http://en.espn.co.uk/era/motorsport/team/292.h...
3  https://en.wikipedia.org/wiki/Maserati_in_moto...
4  https://f1.fandom.com/wiki/Alta_Car_and_Engine...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   constructor_id  168 non-null    object
 1   name            168 non-null    object
 2   nationality     168 non-null    object
 3   Wikipedia_url   44 non-null     object
dtypes: object(4)
memory usage: 5.4+ KB
None
constructor_id      0
name                0
nationality         0
Wikipedia_url     124
dtype: int64

In [31]:
#richiamo le colonne
constructors.columns

Index(['constructor_id', 'name', 'nationality', 'Wikipedia_url'], dtype='object')

In [32]:
constructors

,constructor_id,name,nationality,Wikipedia_url
0,alfa,Alfa Romeo,Swiss,https://en.wikipedia.org/wiki/Alfa_Romeo_in_Fo...
1,lago,Talbot-Lago,French,https://en.wikipedia.org/wiki/Talbot-Lago_T26C
2,era,ERA,British,http://en.espn.co.uk/era/motorsport/team/292.h...
3,maserati,Maserati,Italian,https://en.wikipedia.org/wiki/Maserati_in_moto...
4,alta,Alta,British,https://f1.fandom.com/wiki/Alta_Car_and_Engine...
...,...,...,...,...
163,haas,Haas F1 Team,American,NaN
164,racing_point,Racing Point,British,NaN
165,alphatauri,AlphaTauri,Italian,NaN
166,alpine,Alpine F1 Team,French,NaN
167,rb,RB F1 Team,Italian,NaN

In [33]:
#rinomino le colonne
constructors = constructors.rename(columns={'constructor_id': 'ConstructorID',
                                            'name':'Name', 
                                            'nationality': 'Nationality'}
                                  )
#elimino colonna che non serve
constructors = constructors.drop(columns=["Wikipedia_url"], errors="ignore")

constructors

    ConstructorID            Name Nationality
0            alfa      Alfa Romeo       Swiss
1            lago     Talbot-Lago      French
2             era             ERA     British
3        maserati        Maserati     Italian
4            alta            Alta     British
..            ...             ...         ...
163          haas    Haas F1 Team    American
164  racing_point    Racing Point     British
165    alphatauri      AlphaTauri     Italian
166        alpine  Alpine F1 Team      French
167            rb      RB F1 Team     Italian

[168 rows x 3 columns]

In [34]:
#richiamo i costruttori dal 2014 in poi in una variabile
costruttori_2014_2025 = results["ConstructorID"].unique()
#modifico/filtro i valori della colonna ConstructorID
constructors = constructors[constructors["ConstructorID"].isin(costruttori_2014_2025)]
constructors

    ConstructorID            Name Nationality
0            alfa      Alfa Romeo       Swiss
5         ferrari         Ferrari     Italian
42       mercedes        Mercedes      German
54   aston_martin    Aston Martin     British
94        mclaren         McLaren     British
107      williams        Williams     British
118       renault         Renault      French
139        sauber          Sauber       Swiss
148      red_bull        Red Bull    Austrian
149    toro_rosso      Toro Rosso     Italian
154   force_india     Force India      Indian
159      lotus_f1        Lotus F1     British
160      marussia        Marussia     Russian
161      caterham        Caterham   Malaysian
162         manor  Manor Marussia     British
163          haas    Haas F1 Team    American
164  racing_point    Racing Point     British
165    alphatauri      AlphaTauri     Italian
166        alpine  Alpine F1 Team      French
167            rb      RB F1 Team     Italian

In [35]:
#check valori null
constructors.isna().sum()

ConstructorID    0
Name             0
Nationality      0
dtype: int64

In [36]:
#salvo il dataset pulito
constructors.to_csv("constructors_clean.csv", index=False)

In [37]:
#ultimo dataset drivers
display(drivers.head())
print("______________________________")
print(drivers.info())
print("______________________________")
print(drivers.isna().sum())

     driver_id givenName familyName nationality         dob
0       farina      Nino     Farina     Italian  1906-10-30
1      fagioli     Luigi    Fagioli     Italian  1898-06-09
2  reg_parnell       Reg    Parnell     British  1911-07-02
3    cabantous      Yves  Cabantous      French  1904-10-08
4       rosier     Louis     Rosier      French  1905-11-05

______________________________
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 616 entries, 0 to 615
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   driver_id    616 non-null    object
 1   givenName    616 non-null    object
 2   familyName   616 non-null    object
 3   nationality  616 non-null    object
 4   dob          616 non-null    object
dtypes: object(5)
memory usage: 24.2+ KB
None
______________________________
driver_id      0
givenName      0
familyName     0
nationality    0
dob            0
dtype: int64

In [38]:
#elimino i duplicati
drivers = drivers.drop_duplicates()

In [39]:
#rinomino le colonne
drivers = drivers.rename(columns={'driver_id':'DriverID',
                                  'nationality':'Nationality',
                                  'dob':'BirthDate'}
                        )
drivers

        DriverID    givenName familyName    Nationality   BirthDate
0         farina         Nino     Farina        Italian  1906-10-30
1        fagioli        Luigi    Fagioli        Italian  1898-06-09
2    reg_parnell          Reg    Parnell        British  1911-07-02
3      cabantous         Yves  Cabantous         French  1904-10-08
4         rosier        Louis     Rosier         French  1905-11-05
..           ...          ...        ...            ...         ...
611    antonelli  Andrea Kimi  Antonelli        Italian  2006-08-25
612       lawson         Liam     Lawson  New Zealander  2002-02-11
613    bortoleto      Gabriel  Bortoleto      Brazilian  2004-10-14
614       doohan         Jack     Doohan     Australian  2003-01-20
615       hadjar        Isack     Hadjar         French  2004-09-28

[616 rows x 5 columns]

In [40]:
#unione colonne nome e cognome
drivers['DriverName'] = drivers['givenName'] + ' ' + drivers['familyName']

In [41]:
#elimino le colonne che non servono più
drivers = drivers.drop(columns=['givenName', 'familyName'])

In [42]:
#check
drivers

        DriverID    Nationality   BirthDate             DriverName
0         farina        Italian  1906-10-30            Nino Farina
1        fagioli        Italian  1898-06-09          Luigi Fagioli
2    reg_parnell        British  1911-07-02            Reg Parnell
3      cabantous         French  1904-10-08         Yves Cabantous
4         rosier         French  1905-11-05           Louis Rosier
..           ...            ...         ...                    ...
611    antonelli        Italian  2006-08-25  Andrea Kimi Antonelli
612       lawson  New Zealander  2002-02-11            Liam Lawson
613    bortoleto      Brazilian  2004-10-14      Gabriel Bortoleto
614       doohan     Australian  2003-01-20            Jack Doohan
615       hadjar         French  2004-09-28           Isack Hadjar

[616 rows x 4 columns]

In [43]:
#richiamo i piloti dal 2014 al 2025 in una variabile
drivers_2014_2025 = results["DriverID"].unique()
#filtro nel dataset drivers
drivers = drivers[drivers["DriverID"].isin(drivers_2014_2025)]
drivers

            DriverID    Nationality   BirthDate             DriverName
521           button        British  1980-01-19          Jenson Button
523        raikkonen        Finnish  1979-10-17         Kimi Räikkönen
525           alonso        Spanish  1981-07-29        Fernando Alonso
531            massa      Brazilian  1981-04-25           Felipe Massa
547          rosberg         German  1985-06-27           Nico Rosberg
550         hamilton        British  1985-01-07         Lewis Hamilton
552            sutil         German  1983-01-11           Adrian Sutil
553           kubica         Polish  1984-12-07          Robert Kubica
558           vettel         German  1987-07-03       Sebastian Vettel
561       hulkenberg         German  1987-08-19        Nico Hülkenberg
564        kobayashi       Japanese  1986-09-13        Kamui Kobayashi
569        maldonado     Venezuelan  1985-03-09       Pastor Maldonado
570            perez        Mexican  1990-01-26           Sergio Pérez
571        ricciardo     Australian  1989-07-01       Daniel Ricciardo
572           vergne         French  1990-04-25       Jean-Éric Vergne
574         grosjean         French  1986-04-17        Romain Grosjean
575        gutierrez        Mexican  1991-08-05      Esteban Gutiérrez
576           bottas        Finnish  1989-08-28        Valtteri Bottas
577    jules_bianchi         French  1989-08-03          Jules Bianchi
578          chilton        British  1991-04-21            Max Chilton
580  kevin_magnussen         Danish  1992-10-05        Kevin Magnussen
581            kvyat        Russian  1994-04-26           Daniil Kvyat
582         ericsson        Swedish  1990-09-02        Marcus Ericsson
583             nasr      Brazilian  1992-08-21            Felipe Nasr
584            sainz        Spanish  1994-09-01           Carlos Sainz
585   max_verstappen          Dutch  1997-09-30         Max Verstappen
586            merhi        Spanish  1991-03-22          Roberto Merhi
587          stevens        British  1991-06-28           Will Stevens
588    jolyon_palmer        British  1991-01-20          Jolyon Palmer
589         wehrlein         German  1994-10-18        Pascal Wehrlein
590         haryanto     Indonesian  1993-01-22           Rio Haryanto
591        vandoorne        Belgian  1992-03-26      Stoffel Vandoorne
592             ocon         French  1996-09-17           Esteban Ocon
593       giovinazzi        Italian  1993-12-14     Antonio Giovinazzi
594           stroll       Canadian  1998-10-29           Lance Stroll
595          leclerc     Monegasque  1997-10-16        Charles Leclerc
596  brendon_hartley  New Zealander  1989-11-10        Brendon Hartley
597            gasly         French  1996-02-07           Pierre Gasly
598         sirotkin        Russian  1995-08-27        Sergey Sirotkin
599           norris        British  1999-11-13           Lando Norris
600            albon           Thai  1996-03-23        Alexander Albon
601          russell        British  1998-02-15         George Russell
602           latifi       Canadian  1995-06-29        Nicholas Latifi
603          tsunoda       Japanese  2000-05-11           Yuki Tsunoda
604  mick_schumacher         German  1999-03-22        Mick Schumacher
605          mazepin        Russian  1999-03-02         Nikita Mazepin
606             zhou        Chinese  1999-05-30            Guanyu Zhou
607         sargeant       American  2000-12-31         Logan Sargeant
608         de_vries          Dutch  1995-02-06          Nyck de Vries
609          piastri     Australian  2001-04-06          Oscar Piastri
610          bearman        British  2005-05-08         Oliver Bearman
611        antonelli        Italian  2006-08-25  Andrea Kimi Antonelli
612           lawson  New Zealander  2002-02-11            Liam Lawson
613        bortoleto      Brazilian  2004-10-14      Gabriel Bortoleto
614           doohan     Australian  2003-01-20            Jack Doohan
615           hadjar         French  2004-09-28           Isack Hadjar

In [44]:
#salvo le modifiche
drivers.to_csv("drivers_clean.csv", index=False)

In [46]:
#Carico i file CSV
constructors_stands = pd.read_csv('constructor_standings.csv')
drivers_stands = pd.read_csv('driver_standings.csv')

constructors_stands

      season  round constructor_id  position  points  wins
0       1950      7           alfa       NaN     0.0     6
1       1950      7   kurtis_kraft       NaN     0.0     1
2       1950      7        ferrari       NaN     0.0     0
3       1950      7          deidt       NaN     0.0     0
4       1950      7           lago       NaN     0.0     0
...      ...    ...            ...       ...     ...   ...
1056    2025     21             rb       6.0    82.0     0
1057    2025     21   aston_martin       7.0    72.0     0
1058    2025     21           haas       8.0    70.0     0
1059    2025     21         sauber       9.0    62.0     0
1060    2025     21         alpine      10.0    22.0     0

[1061 rows x 6 columns]

In [47]:
drivers_stands

      season  round  driver_id  position  points  wins
0       1950      7     farina       1.0    30.0     3
1       1950      7     fangio       2.0    27.0     3
2       1950      7    fagioli       3.0    24.0     0
3       1950      7     rosier       4.0    13.0     0
4       1950      7     ascari       5.0    11.0     0
...      ...    ...        ...       ...     ...   ...
3126    2025     21    tsunoda      17.0    32.0     0
3127    2025     21      gasly      18.0    22.0     0
3128    2025     21  bortoleto      19.0    19.0     0
3129    2025     21  colapinto      20.0     0.0     0
3130    2025     21     doohan      21.0     0.0     0

[3131 rows x 6 columns]

In [50]:
#filtro per season
constructors_stands = constructors_stands[constructors_stands['season'] >= 2014]
drivers_stands = drivers_stands[drivers_stands['season'] >= 2014]

In [51]:
drivers_stands

      season  round  driver_id  position  points  wins
2863    2014     19   hamilton       1.0   384.0    11
2864    2014     19    rosberg       2.0   317.0     5
2865    2014     19  ricciardo       3.0   238.0     3
2866    2014     19     bottas       4.0   186.0     0
2867    2014     19     vettel       5.0   167.0     0
...      ...    ...        ...       ...     ...   ...
3126    2025     21    tsunoda      17.0    32.0     0
3127    2025     21      gasly      18.0    22.0     0
3128    2025     21  bortoleto      19.0    19.0     0
3129    2025     21  colapinto      20.0     0.0     0
3130    2025     21     doohan      21.0     0.0     0

[268 rows x 6 columns]

In [53]:
constructors_stands

      season  round constructor_id  position  points  wins
939     2014     19       mercedes       1.0   701.0    16
940     2014     19       red_bull       2.0   405.0     3
941     2014     19       williams       3.0   320.0     0
942     2014     19        ferrari       4.0   216.0     0
943     2014     19        mclaren       5.0   181.0     0
...      ...    ...            ...       ...     ...   ...
1056    2025     21             rb       6.0    82.0     0
1057    2025     21   aston_martin       7.0    72.0     0
1058    2025     21           haas       8.0    70.0     0
1059    2025     21         sauber       9.0    62.0     0
1060    2025     21         alpine      10.0    22.0     0

[122 rows x 6 columns]

In [59]:
constructors_stands.info()

<class 'pandas.core.frame.DataFrame'>
Index: 122 entries, 939 to 1060
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   season          122 non-null    int64
 1   round           122 non-null    int64
 2   constructor_id  122 non-null    object
 3   position        122 non-null    float64
 4   points          122 non-null    float64
 5   wins            122 non-null    int64
dtypes: float64(2), int64(3), object(1)
memory usage: 6.7+ KB

In [60]:
# Applico il filtro a posizione uguale a 1 per vedere solo i campioni
c_leaders = constructors_stands[(constructors_stands['position'] == 1.0)]
d_leaders = drivers_stands[(drivers_stands['position'] == 1.0)]

In [61]:
c_leaders

      season  round constructor_id  position  points  wins
939     2014     19       mercedes       1.0   701.0    16
950     2015     19       mercedes       1.0   703.0    16
960     2016     21       mercedes       1.0   765.0    19
971     2017     20       mercedes       1.0   668.0    12
981     2018     21       mercedes       1.0   655.0    11
991     2019     21       mercedes       1.0   739.0    15
1001    2020     17       mercedes       1.0   573.0    13
1011    2021     22       mercedes       1.0   613.5     9
1021    2022     22       red_bull       1.0   759.0    17
1031    2023     22       red_bull       1.0   860.0    21
1041    2024     24        mclaren       1.0   666.0     6
1051    2025     21        mclaren       1.0   756.0    14

In [62]:
d_leaders

      season  round       driver_id  position  points  wins
2863    2014     19        hamilton       1.0   384.0    11
2887    2015     19        hamilton       1.0   381.0    10
2909    2016     21         rosberg       1.0   385.0     9
2933    2017     20        hamilton       1.0   363.0     9
2958    2018     21        hamilton       1.0   408.0    11
2978    2019     21        hamilton       1.0   413.0    11
2998    2020     17        hamilton       1.0   347.0    11
3021    2021     22  max_verstappen       1.0   395.5    10
3042    2022     22  max_verstappen       1.0   454.0    15
3064    2023     22  max_verstappen       1.0   575.0    19
3086    2024     24  max_verstappen       1.0   437.0     9
3110    2025     21          norris       1.0   408.0     7

In [63]:
#salvataggio in nuovi csv puliti
c_leaders.to_csv('constructor_champions.csv', index=False)
d_leaders.to_csv('driver_champions.csv', index=False)